---
# This playbook deploys foreman together with passenger_nginx and mysql
# including foreman-proxy, tftp and dhcp
- hosts: infrastructure 
  vars_files:
    - vars/example.yml
  roles:
    - { role: pre }
    - { role: common }
    - { role: puppet-master }

